services:
  postgres:
    image: postgres
    volumes:
      - ./base-general.sql:/docker-entrypoint-initdb.d/base-general.sql
    environment:
      POSTGRES_PASSWORD: "pass"
      POSTGRES_USER: "estacionamento"
      POSTGRES_DB: "estacionamento_db"
    ports:
      - "5432:5432"